#!/usr/bin/env bash

set -e

if ! type "php" &> /dev/null;
then
    echo 'Error: "PHP" not installed'; exit 1;
fi

if ! type "unzip" &> /dev/null;
then
    echo 'Error: "unzip" not installed'; exit 1;
fi

if ! type "sed" &> /dev/null;
then
    echo 'Error: "sed" not installed'; exit 1;
fi

ROOT=$(pwd)

if [ ! -z "$(ls -A $ROOT)" ];
then
    echo 'Error: This script only works in an empty directory.'; exit 1;
fi

echo 'Downloading WordPress...'
cd $ROOT
wget -q https://wordpress.org/latest.zip &> /dev/null
unzip -qq latest.zip
mv wordpress/* .
rm -rf latest.zip
rm -rf wordpress
wget -q https://raw.githubusercontent.com/luizbills/create-wordpress-sqlite/main/files/wp-config.php  &> /dev/null

cd $ROOT/wp-content/plugins/

echo 'Downloading SQLite Database Integration plugin...'
wget -q https://downloads.wordpress.org/plugin/sqlite-database-integration.zip &> /dev/null
unzip -qq sqlite-database-integration.zip
rm -rf sqlite-database-integration.zip

PLUGIN_DIR="$ROOT/wp-content/plugins/sqlite-database-integration"

cp $PLUGIN_DIR/db.copy $ROOT/wp-content/db.php
sed -i "s#{SQLITE_IMPLEMENTATION_FOLDER_PATH}#$PLUGIN_DIR#" $ROOT/wp-content/db.php
sed -i 's#{SQLITE_PLUGIN}#sqlite-database-integration/load.php#' $ROOT/wp-content/db.php

echo 'Downloading Adminer installer...'
mkdir $ROOT/adminer
cd $ROOT/adminer
wget -q https://raw.githubusercontent.com/luizbills/create-wordpress-sqlite/main/files/adminer/install.sh &> /dev/null
chmod +x $ROOT/adminer/install.sh

echo 'Finishing...'
cd $ROOT
echo "php -S localhost:8080" > $ROOT/start-server.sh
chmod +x $ROOT/start-server.sh

echo 'DONE!'
echo 'Run ./start-server.sh to start your WordPress server'
echo 'Optional: run ./adminer/install.sh to install and setup Adminer database editor'
